sudo: required
language: java
jdk: oraclejdk8

branches:
  only: master

cache:
  directories:
- "$HOME/.m2"

before_script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn test -B
