sudo: required

deploy:
  provider: releases
  api_key:
    secure: vjL2gCBtJUa/lBhjM89LEuBUnRUkGEprxzrZSilpm1tgf+kBEIOn13Ohn4XouKH1OC3yAzxLzfLE+vi0KlvXNDwltipMaRgVOAMWK6NRIlVsrtX1vS+U+2lIUQHtXGHHRdNJn9sfcI5Y+acKQMUx5oSkkp50Bq2WWez2uNrEBlMDrcfrigWSu8MhD8DVZ2M62Qg0Azx9ZpprjiKVwfdBirXzqUugI5wnvsWkrdQcneiKbhVN+OL8WPPwSHp5CvkFdNqM2qfPjPwr2PC3VtVLr1Ahy4r7jzMGLaFXFJq8wZgf3bsKqO+6lEyUXYYNtSNtKn1Njw615KVz8FKtBulJBlNQQq9lNFR6tIVlFusjMfRkfLjYZ9S15PXHbdIfqoD4wB9R7wuVsR72g+CmMbHBRgjgnMhbOR+cA5cr2B5EvtvbTW89ULC1Vn1dfr4kBimvvtOp8GgiAU3NfATnFj/KuZIDVTNR8dfW63/eC3lcKf2DFtiQbPsIY926ucLu43k4YN7hKGsdmmfELjl5u3WL9SU9e3suJHQ2oJmBnJ+nUJQYpUHz4fw2yqndT+lXZFISO4RpJp6CvLF0E7M9DemFNUl01aTAzAmiQIh6+cW9QDXxSDb22GzgCiE4O/7X32jvQ2vmlA+tw04llSMG21L0j/Ir2+QYoE4rj8/lXSG/nJs=
  file: target/cdp4j.jar
  skip_cleanup: true
  on:
    tags: true

language: java

jdk: oraclejdk8

dist: trusty 

branches: master

cache:
  directories:
  - $HOME/.m2

before_install:  
 - sudo apt-get install libxss1 libappindicator1 libindicator7
 - mkdir -p chrome-archive
 - wget -qnc https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O chrome-archive/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i chrome-archive/google-chrome*.deb # Might show "errors", fixed by next line
 - sudo apt-get install -f

before_script:
 - mvn -q clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- google-chrome --version
- google-chrome --headless --no-default-browser-check --no-first-run --disable-translate --remote-debugging-port=9222 --disable-gpu &
- mvn clean test
- wget https://github.com/codacy/codacy-coverage-reporter/releases/download/2.0.0/codacy-coverage-reporter-2.0.0-assembly.jar -O codacy.jar
- java -cp codacy.jar com.codacy.CodacyCoverageReporter -l Java -r target/site/jacoco/jacoco.xml